version: "3.9"
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:4000/api
    depends_on:
      - backend

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../backend:/app
    command: sh -c "npm install && npx prisma generate && npm run dev"
    ports:
      - "4000:4000"
    env_file:
      - ../backend/.env
