const fallbackUrl = "https://example.com";

function normalizeUrl(url: string): string {
  return url.endsWith("/") ? url.slice(0, -1) : url;
}

export const siteConfig = {
  name: "ISHU.FUN",
  title: "ISHU.FUN | Admin-Curated Streaming Platform",
  description:
    "ISHU.FUN is a modern, fast video platform with admin-only publishing, 50+ category hubs, structured SEO, and smooth product-grade UX inspired by top global product websites like YouTube, Apple, Vercel, and Tesla.",
  url: normalizeUrl(process.env.NEXT_PUBLIC_SITE_URL || fallbackUrl),
  adminHidePath: (process.env.NEXT_PUBLIC_ADMIN_HIDE_PATH || "control-room-9x72").replace(/^\/+|\/+$/g, ""),
  defaultOgImage: "/images/og/ishu-og-grid.svg",
  themeColor: "#05050b",
  locale: "en_US",
  brandAliases: ["ISHU", "ISHU FUN", "ISHU.FUN", "IshuFun", "ishufun videos", "ishu fun", "ishufun", "ishu.fun"],
  brandSlogans: [
    "Stream smarter with ISHU.FUN",
    "Admin-curated video streaming",
    "50+ categories, one platform",
    "Premium video discovery",
  ],
  socialProfiles: [
    "https://github.com/ISHUKR41",
    "https://www.youtube.com/",
    "https://x.com/",
    "https://www.instagram.com/",
  ],
  keywords: [
    "ishu",
    "ishu.fun",
    "ishufun",
    "ishu fun",
    "ishufun videos",
    "ishu reels",
    "ishu clips",
    "ishu video app",
    "ishu.fun streaming",
    "ishu.fun upload platform",
    "ishu modern website",
    "ishu seo optimized website",
    "ishu fun videos",
    "ishu video platform",
    "ishu streaming",
    "ishu creator platform",
    "ishufun video upload",
    "ishufun category videos",
    "ishu.fun categories",
    "ishu.fun admin platform",
    "ishu.fun video upload",
    "ishu.fun HD videos",
    "ishu.fun 4K streaming",
    "ishu.fun live streams",
    "ishu.fun trending",
    "ishu.fun best videos",
    "ishu.fun watch online",
    "ishu.fun free videos",
    "ishu.fun premium content",
    "ishu.fun verified creators",
    "ishu.fun community",
    "ishu.fun Indian videos",
    "ishu.fun entertainment",
    "ishu fun website",
    "ishu fun app",
    "ishu fun watch",
    "ishu fun stream",
    "ishu fun discover",
    "ishufun online",
    "ishufun platform",
    "ishufun streaming site",
    "ishu.fun dark mode",
    "ishu.fun modern design",
    "ishu.fun glassmorphism",
    "ishu.fun 3d website",
    "ishu.fun smooth scrolling",
    "ishu.fun professional",
    "ishu.fun production ready",
    "ishu.fun deployment",
    "ishu.fun vercel deploy",
    "ishu.fun next.js",
    "ishu.fun react",
    "ishu.fun typescript",
    "ishu online videos",
    "ishu watch free",
    "ishu best streaming",
    "ishu top videos",
    "ishu trending clips",
    "ishu hot videos",
    "ishu new uploads",
    "ishu latest videos",
    "ishu popular content",
    "ishu viral videos",
    "ishu exclusive content",
    "ishu curated library",
    "ishu recommended videos",
    "ishu featured content",
    "ishu discovery engine",
    "ishu video search",
    "video platform",
    "admin curated videos",
    "admin only video uploads",
    "modern streaming website",
    "youtube style platform",
    "youtube like upload flow",
    "youtube inspired streaming",
    "category based discovery",
    "seo optimized video site",
    "ai seo assistant",
    "seo ai",
    "seo optimization",
    "seo keywords",
    "search ranking video platform",
    "smooth scrolling website",
    "lag free website",
    "high performance website",
    "fast smooth scrolling",
    "professional animated website",
    "professional icons website",
    "modern dark theme website",
    "structured data seo",
    "schema markup video website",
    "json ld website",
    "fast video discovery",
    "50 category pages",
    "50 categories separate pages",
    "50 categories separate folders",
    "category rename auto update",
    "admin hidden upload page",
    "modern creator website",
    "smooth scrolling web app",
    "seo ai optimization",
    "video streaming platform",
    "premium video website",
    "professional video hosting",
    "category video platform",
    "modern web design",
    "3d animated website",
    "apple inspired design",
    "vercel style platform",
    "tesla inspired ui",
    "google material design",
    "microsoft fluent design",
    "stripe checkout experience",
    "figma collaborative design",
    "notion workspace design",
    "framer style animations",
    "airhub style interface",
    "rupay inspired trust UI",
    "flipkart inspired ux",
    "airbnb user experience",
    "nike brand design",
    "dropbox file sharing",
    "github developer platform",
    "google inspired ui",
    "microsoft inspired ui",
    "apple inspired ui",
    "tesla inspired website",
    "vercel inspired website",
    "video content management",
    "video cms platform",
    "professional video site",
    "enterprise video platform",
    "video hosting service",
    "video sharing network",
    "glassmorphism web design",
    "dark mode video platform",
    "responsive video website",
    "mobile friendly streaming",
    "next generation video platform",
    "web3 video platform",
    "creator economy platform",
    "content creator tools",
    "video SEO optimization",
    "video metadata management",
    "comment moderation system",
    "curated video library",
    "video discovery engine",
    "trending video platform",
    "lazy loading video site",
    "dynamic loading streaming",
    "performance optimized website",
    "gpu accelerated animations",
    "60fps smooth website",
    "production ready website",
    "zero error deployment",
    "vercel deployment ready",
  ],
} as const;

export function absoluteUrl(pathname: string): string {
  if (!pathname.startsWith("/")) {
    return `${siteConfig.url}/${pathname}`;
  }

  return `${siteConfig.url}${pathname}`;
}
